Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Metrics/MethodLength:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Metrics/AbcSize:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
