Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Metrics/MethodLength:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Metrics/AbcSize:
  Exclude:
    - 'cnfs-core/lib/cnfs/core/schema.rb'
Style/ClassAndModuleChildren:
  Enabled: false
