AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 120
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - cli/app/helpers/*
Metrics/CyclomaticComplexity:
  Exclude:
    - cli/app/helpers/*
Metrics/MethodLength:
  Exclude:
    - cli/app/helpers/*
  IgnoredMethods:
    - create_table
Metrics/PerceivedComplexity:
  Exclude:
    - cli/app/helpers/*
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
