#!/usr/bin/env ruby
# frozen_string_literal: true

{ 'cli' => 'cnfs-cli', 'infra' => 'cnfs-cli-infra', 'backend' => 'cnfs-cli-backend' }.each_pair do |dir, name|
  name ||= dir
  Dir.chdir(dir) do
    puts "gem build #{name}.gemspec"
    puts "gem install ./#{name}-0.1.0.gem" if ARGV.include?('-i')
  end
end
