#!/usr/bin/env ruby
# frozen_string_literal: true

Dir['*/'].each do |dir|
  Dir.chdir(dir) do
    next unless (gemspec = Dir['*.gemspec'].shift)
    cmd = "gem build #{gemspec}"
    if ARGV.include?('-d')
      puts cmd
    else
      `#{cmd}`
    end
    next unless ARGV.include?('-i')
    cmd = "gem install ./#{gemspec.delete_suffix('.gemspec')}-0.1.0.gem"
    if ARGV.include?('-d')
      puts cmd
    else
      `#{cmd}`
    end
  end
end
