#!/usr/bin/env ruby
# frozen_string_literal: true
require 'fileutils'
require 'thor'

class GemController < Thor
  class_option :noop, desc: 'Do not execute commands',
    aliases: '-n', type: :boolean
  class_option :verbose, desc: 'Display extra information from command',
    aliases: '-v', type: :boolean

  desc 'install', 'Install all gems locally from source'
  def install
    each_dir do |gemspec|
      exec("gem build #{gemspec}")
      next unless (gem = Dir['*.gem'].shift)

      exec("gem install ./#{gem}")
      FileUtils.rm(gem)
    end
  end

  desc 'uninstall', 'Uninstall all gems'
  def uninstall
    each_dir do |gemspec|
      exec("gem uninstall -a -x #{gemspec.delete_suffix('.gemspec')}")
    end
  end

  private

  def each_dir
    Dir['*/'].each do |dir|
      Dir.chdir(dir) do
        next unless (gemspec = Dir['*.gemspec'].shift)

        yield gemspec
      end
    end
  end

  def exec(cmd)
    puts cmd if options.verbose
    `#{cmd}` unless options.noop
  end
end

GemController.start
