#!/usr/bin/env ruby
# #!/usr/bin/env bash
# set -euo pipefail
# IFS=$'\n\t'
# set -vx

require 'fileutils'

def each_dir
  Dir['*/'].sort.each do |dir|
    dir = dir.delete_suffix('/')
    Dir.chdir(dir) do
      next unless (gemspec = Dir['*.gemspec'].shift)
      if (gemfile = Dir['*.gem'].shift)
        FileUtils.rm(gemfile)
      end

      yield # dir, gemspec
    end
  end
end

each_dir do
  puts "** #{Dir.pwd.split('/').last}"
  File.open('Gemfile', 'w') { |f| f.write("source ENV['GEM_SERVER'] || 'https://rubygems.org'\ngemspec") }
  system('bundle install')
  FileUtils.rm('Gemfile')
  FileUtils.rm('Gemfile.lock')
end
