# frozen_string_literal: true

source 'https://rubygems.org'

gem_path = '/home/admin/cnfs'

gem 'solid_record', path: "#{gem_path}/solid_record"
gem 'solid_support', path: "#{gem_path}/solid_support"

gemspec

gem 'pry'
