#!/usr/bin/env ruby
# frozen_string_literal: true

git_path = File.expand_path("../../.git", __dir__)

if File.exist?(git_path)
  ENV['CNFS_CLI_ENV'] ||= 'development'
  require 'pry'
  plugin_path = File.expand_path("../lib", __dir__)
  $:.unshift(plugin_path)
end

ENV['CNFS_CLI_ENV'] ||= 'production'

ROOT_FILE_ID = 'config/environment.rb'

require 'cnfs/boot_loader'
