# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pry'
gem 'pry-byebug'
gem 'onestack', path: '../..'
gem 'solid_support', path: '../../../solid_support'
gem 'solid_record', path: '../../../solid_record'
