---
inherit_from: ../.rubocop.yml
AllCops:
  Exclude:
    - 'lib/solid_record/associations.rb'
Lint/EmptyClass:
  Exclude:
    - 'spec/**/*.rb'
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
Style/CommentedKeyword:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 7
