# environments/development/application/backend.yml
---
localstack:
  environment:
    services: s3:4572,lambda:4574,sns:4575,sqs:4576
    port_web_ui: 8080
    debug: s3
    hostname: localstack
    hostname_external: localstack
nginx:
postgres:
  environment:
    username: user
    password: password
redis:
wait:
  depends_on: ['localstack', 'postgres', 'redis']
