# contexts.yml
# target with no application is all applications
# application with no target is all targets
---
DEFAULTS: &DEFAULTS
  name: $LABEL

bd: &bd
  <<: *DEFAULTS
  target: development
  application: backend

fd: &fd
  <<: *DEFAULTS
  target: development
  application: frontend

pd: &pd
  <<: *DEFAULTS
  target: development
  application: pipeline
