# config/environments/development/backend/application/rails.yml
---
config:
  image:
    static_gems:
      bundler: 2.0.1
      eventmachine: 1.2.7
      ffi: 1.10.0
      mini_portile2: 2.4.0
      msgpack: 1.2.10
      nio4r: 2.3.1
      nokogiri: 1.10.4
      pg: 1.1.4
      puma: 3.12.1
    build_args:
      rails_env: development
      bundle_string: --without production
      os_packages: ['libpq5', 'tree', 'curl', 'git', 'sudo', 'vim', 'less', 'tcpdump', 'net-tools', 'iputils-ping', 'graphviz']
