FROM ruby:2.7.1-buster as base

# WORKDIR needs to be the same as in the final base image or compiled gems will point to an invalid directory
# NOTE: For the compiled gems to be shared across services then the WORKDIR needs to be same for all images
RUN mkdir -p /home/rails/services/app
WORKDIR /home/rails/services/app
ENV GEM_HOME=/usr/local/bundle/ruby/2.7.0
ENV PATH $GEM_HOME/bin:$PATH

# Install gems that need compiling first b/c they can take a long time to compile
RUN gem install \
    <%= dockerfile_gems %>

RUN gem install <%= dockerfile_bundler %>

# sources are based on where the code resides on the host system relative to the build directory
# targets are based on where the Gemfile expects to find them within the container
# NOTE: Copy in a generic Gemfile and the dependent gem's gemspecs so that their dependencies are also installed

ARG source_path=<%= cnfs.repo_name %>
ARG target_path=<%= cnfs.repo_path %>

COPY ${source_path}/lib/core/*.gemspec ${target_path}/lib/core/
COPY ${source_path}/lib/sdk/*.gemspec ${target_path}/lib/sdk/
COPY ${source_path}/services/Gemfile ./
