# config/infra/backend.yml
---
backend:
  dns:
    root_domain: localhost
    sub_domain:
    endpoints:
      grafana: grafana
      api:
        scheme: https
        host: api
      sftp:
        host: sftp
  object_storage:
    buckets:
      app:
        services: ['documents', 'reports', 'sftp']
      cdn:
        services: ['images']

