#!/usr/bin/env ruby
# frozen_string_literal: true

git_path = File.expand_path('../../.git', __dir__)

if File.exist?(git_path)
  plugin_path = File.expand_path('../lib', __dir__)
  $:.unshift(plugin_path)
end

require 'solid_support'
require 'solid_support/boot_loader'
