#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require 'cnfs'

lite_setup =  ARGV[0].blank? || %w[version help new].include?(ARGV[0])
Cnfs.setup(lite_setup)

unless Cnfs.project? || lite_setup
  STDOUT.puts('WARN: not a cnfs project')
  return
end

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  PrimaryController.start
rescue Cnfs::Error => e
  puts "ERROR: #{e.message}"
  exit 1
end
