#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

ENV['CNFS_CLI_DEV'] ||= ARGV.delete('--cli-dev')
dval = ARGV.index('--debug') || ARGV.index('-d')
ENV['CNFS_DEBUG'] = ARGV[dval + 1] if dval
dval = ARGV.index('--logging') || ARGV.index('-l')
ENV['CNFS_LOGGING'] = ARGV[dval + 1] if dval

require 'cnfs'

# Signal.trap('INT') do
#   warn("\n#{caller.join("\n")}: interrupted")
#   # exit 1
# end

begin
  Cnfs.initialize!
rescue Cnfs::Error => e
  puts e.message
  exit 2
end
