#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)

require 'cnfs'

if not Cnfs.cnfs_project? and not ARGV[0].eql?('version')
  STDOUT.puts('WARN: not a cnfs project')
  return
end

Cnfs.setup

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

require 'cnfs/cli'

begin
  Cnfs::Cli.start
rescue Cnfs::Cli::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
