#

# Gems to install on a clean machine to be used for development of this gem
source ENV['GEM_SERVER'] || 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'thor'
gem 'activesupport'
