# frozen_string_literal: true

source 'https://rubygems.org'

root_path =  '../../../../'

gem 'cnfs', path: "#{root_path}/cnfs"
gem 'cnfs-core', path: "#{root_path}/core"
gem 'cnfs-aws', path: "#{root_path}/aws"
gem 'cnfs-docker', path: "#{root_path}/docker"
gem 'cnfs-gcp', path: "#{root_path}/gcp"
gem 'cnfs-kubernetes', path: "#{root_path}/kubernetes"
gem 'cnfs-native', path: "#{root_path}/native"
gem 'cnfs-packer', path: "#{root_path}/packer"
gem 'cnfs-terraform', path: "#{root_path}/terraform"

gem 'cnfs-backend', path: '/home/admin/cnfs-components/backend'

gem 'guard-rspec'
