#!/usr/bin/env bash

# we cannot exec the {docker,podman}-compose invocation as we need to run the
# 'down' command to properly clean things up

set -eEuo pipefail

name=$(basename $0 | cut -f2 -d '_')

_docker() {
  local cmd=$1
  local file=${name}.yml

  docker-compose \
    -f $file \
    $cmd
}

if [ $(uname -s) == "Darwin" ]; then
  export TMPDIR=/private${TMPDIR:-""}
fi

_podman() {
  local cmd=$1
  local file=${name}.yml

  # for reasons unknown localstack and eleasticsearch do not come up without -t
  # hostnet although the other services are fine. Additionally, with systemd 243
  # the perms on /dev/net/tun are wrong, so we would have to manually set them
  # to 666 first (fixed in systemd 244)
  podman-compose \
    -t hostnet \
    -f $file \
    $cmd
}

install -dm777 $TMPDIR/$name

if command -v podman-compose >/dev/null; then
  _podman up || true
  _podman down || true
elif command -v docker-compose >/dev/null && docker version >/dev/null 2>&1; then
  _docker up || true
  _docker down || true
else
  echo "$name is not available"
  sleep 9999d
fi
