#!/usr/bin/env bash

set -eEuo pipefail

name=$1
dir=$2/$name
port=${3:-0}

app=$(basename "$0" .sh)

. libexec/lib.sh

cd "$dir"
if [ -d spec/dummy ]; then
  app_dir=spec/dummy
else
  app_dir=.
fi

if [ -e Gemfile ]; then
  export BUNDLE_GEMFILE=$(pwd)/Gemfile
fi

install_gems_maybe

case $app in
  _rails)
    migrate_and_seed_db_maybe $(db_name_for_service $name)
    exec bundle exec rails s -p "$port"
    ;;
  _scheduler)
    exec sleep 9999d
    ;;
  _sidekiq)
    exec bundle exec sidekiq -r $app_dir -C config/sidekiq.yml
    ;;
  _spring)
    bundle exec spring stop || true
    if [ ${VERBOSE_SPRING:-0} -eq 1 ]; then
      exec bundle exec spring server
    else
      exec bundle exec spring server >/dev/null
    fi
    ;;
esac
