# builders.yml
---
terraform:
  type: Builder::Terraform
  providers:
    aws:
      version: 3.22
  dependencies:
    - name: terraform-provider-restapi_v1.10.0
      url: https://github.com/Mastercard/terraform-provider-restapi/releases/download/v1.10.0/terraform-provider-restapi_v1.10.0-${platform}-amd64
    - name: terraform-provider-kubectl
      url: https://github.com/gavinbunney/terraform-provider-kubectl/releases/download/v1.0.2/terraform-provider-kubectl-${platform}-amd64
vagrant:
  type: Builder::Vagrant
  config:
    box: ros/generic
    box_url: https://perx-ros-boxes.s3-ap-southeast-1.amazonaws.com/vagrant/json/ros/generic.json
  dependencies:
    - name: setup
      type: repo
      url: https://github.com/rails-on-services/setup
ansible:
  type: Builder::Ansible
  dependencies:
    - name: setup
      type: repo
      url: https://github.com/rails-on-services/setup
