# builders.yml
---
terraform:
  type: Builder::Terraform
  config:
    custom_providers:
      - name: terraform-provider-restapi_v1.10.0
        url: https://github.com/Mastercard/terraform-provider-restapi/releases/download/v1.10.0/terraform-provider-restapi_v1.10.0-{platform}-amd64
      - name: terraform-provider-kubectl
        url: https://github.com/gavinbunney/terraform-provider-kubectl/releases/download/v1.0.2/terraform-provider-kubectl-{platform}-amd64
