# deployments.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL
  config:
    base_path: cnfs_tmp

frontend_development: &frontend_development
  <<: *DEFAULTS
  application: frontend
  target: development

frontend_test: &frontend_test
  <<: *DEFAULTS
  application: frontend
  target: test

frontend_production: &frontend_production
  <<: *DEFAULTS
  application: frontend
  target: production

backend_development: &backend_development
  <<: *DEFAULTS
  application: backend
  target: development

backend_test: &backend_test
  <<: *DEFAULTS
  application: backend
  target: test

backend_production: &backend_production
  <<: *DEFAULTS
  application: backend
  target: production

pipeline_development: &pipeline_development
  <<: *DEFAULTS
  application: pipeline
  target: development

pipeline_test: &pipeline_test
  <<: *DEFAULTS
  application: pipeline
  target: test

pipeline_production: &pipeline_production
  <<: *DEFAULTS
  application: pipeline
  target: production

<%= Cnfs.config_content(:project, __FILE__) %>
<%= Cnfs.config_content(:user, __FILE__) %>
