# runtimes.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL

compose: &compose
  <<: *DEFAULTS
  type: Runtime::Compose
  config:
    version: 3.2

native: &native
  <<: *DEFAULTS
  type: Runtime::Native
  config:
    version: 1

<%= Cnfs.load_configs(__FILE__) %>
