# runtimes.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL

compose:
  <<: *DEFAULTS
  type: Runtime::Compose
  config:
    version: 3.2

native:
  <<: *DEFAULTS
  type: Runtime::Native

<%= Cnfs.load_configs(__FILE__) %>
