# targets.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL
  type: Target::Instance
  runtime: compose
  provider: localstack
  config:
    application_environment: development

development: &development
  <<: *DEFAULTS 
  services: localstack, postgres, redis, nginx, wait
  # TODO: resources are in addition to the resources specified by the type
  # resources: instance # instance resource contains dns records, alb, instance, etc
  # layers: dev_cloud, cloud_networking, cluster, dev_cluster, cluster_database # dev_database
  config:
    application_environment: development
    mount: yes
    # dns_root_domain: localhost
    dns_root_domain: demo.cnfs.io
    dns_sub_domain: development
    lb_dns_hostnames: ['api']
    root_domain_managed_in_route53: yes
  environment:
    from_target: target_value

test: &test
  <<: *DEFAULTS 

production: &production
  <<: *DEFAULTS 
  type: Target::Kubernetes
  resources: postgres, redis, kubernetes
  runtime: skaffold
  infra_runtime: terraform
  config:
    # TODO: move ENVs to deployments so application_environment is removed
    application_environment: production
    dns_root_domain: infra-testing.perxtech.io
    dns_sub_domain: development
    root_domain_managed_in_route53: yes
    lb_dns_hostnames: ['api']
  tf_config:
    tags:
      environment: staging

<%= Cnfs.load_configs(__FILE__) %>
