---
s-file-1:
    ip: 10.1.1.72
    kind: Dc
    shares: []
s-file-2:
    kind: AFile
    shares:
    - drive: p
      path: ClientApps
      purpose: apps
    - drive: w
      path: WPKG
      purpose: wpkg
    version: 2008r2
s-hyperv-1:
    ip: 10.1.1.55
    kind: Hv
    shares: []
s-hyperv-2:
    ip: 10.1.1.59
    kind: Imm
    shares: []
s-file-3:
    kind: AFile
    shares:
    - drive: p
      path: ClientApps
      purpose: apps
    - drive: w
      path: WPKG
      purpose: wpkg
    version: '2016'
s-fw-1:
    kind: Firewall
    shares: []
    services:
    - name: ssh
      port: 7430
