---
config:
  provider: amazon

cdn:
  config:
    provider: amazon_sg
  cdn:
    enabled: yes
    bucket: cdn
    url: https://cdn.uat.demo.cnfs.io
dns:
  root_domain: localhost
  # sub_domain:
  endpoints:
    api:
      scheme: https
      host: api
    cdn:
      scheme: https
      host: cdn
      feature_set: directory
    grafana:
      host: grafana
    sftp:
      host: sftp
instance:
  type: t2
kubernetes:
  units:
    fluentd:
    grafana:
    prometheus:
object_storage:
  buckets:
    app:
      services: ['documents', 'reports', 'sftp']
    cdn:
      services: ['images']
