# layers.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL

core: &gem_core
  <<: *DEFAULTS

# This provides a default; Expect to override in project config
business:
  <<: *gem_core

dev_database:
  <<: *DEFAULTS

cluster_database:
  <<: *DEFAULTS

aaa:
  <<: *DEFAULTS

storage:
  <<: *DEFAULTS

dev_cloud:
  <<: *DEFAULTS

dev_cluster:
  <<: *DEFAULTS

cluster:
  <<: *DEFAULTS

cloud_networking:
  <<: *DEFAULTS

networking:
  <<: *DEFAULTS

cdns:
  <<: *DEFAULTS

dns:
  <<: *DEFAULTS

<%= Cnfs::Core.fixture_content(:project, __FILE__) %>
<%= Cnfs::Core.fixture_content(:user, __FILE__) %>
