# providers.yml
---
DEFAULTS: &DEFAULTS
  amazon: &AMAZON_DEFAULTS
    type: Provider::Aws
    config:
      tf_version: '>= 2.38.0'
  alicloud: &ALICLOUD_DEFAULTS
    name: $LABEL
    type: Provider::Alicloud
  azure: &AZURE_DEFAULTS
    name: $LABEL
    type: Provider::Azure
  gcp: &GCP_DEFAULTS
    name: $LABEL
    type: Provider::Gcp

aws_sg:
  <<: *AMAZON_DEFAULTS

localstack:
  name: $LABEL
  type: Provider::Aws
  config:
    account_id: 251316246111
    access_key_id: 1LCDE/udAJWIsU/3No34RCcQvCvJ0pQ0qorJbbtQqaDnaXQKVC5TTdJdzxZCgG90
    secret_access_key: BzGkgBy5tpHDlDduhiU8FKgAXe9hZwwHcm2AUuL1v1rSM082pj7yg3Mt7MJPHM0D5bWgLze8g9UctNUDSn+Iax+KEWM=
    region: ap-southeast-1
    storage:
      endpoint: http://localstack:4576
      region: localstack
    mq:
      endpoint: http://localstack:4572
      region: localstack

<%= Cnfs::Core.project_fixture_content(__FILE__) %>
