# services.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL

wait:
  <<: *DEFAULTS
  type: Service::Wait
  layer: dev_cloud

localstack:
  <<: *DEFAULTS
  layer: dev_cloud
  environment:
    self:
      services: s3:4572,lambda:4574,sns:4575,sqs:4576
      port_web_ui: 8080
      debug: s3
      hostname: localstack
      hostname_external: localstack

nginx:
  <<: *DEFAULTS
  type: Service::Nginx
  # layer: dev_networking
  layer: dev_cloud

postgres:
  <<: *DEFAULTS
  layer: dev_database
  environment:
    self:
      postgres_user: admin
      postgres_password: admin
      postgres_db: postgres
    application:
      rails_database_host: postgres
      # rails_database_user: admin
      # rails_database_password: admin

redis:
  <<: *DEFAULTS
  layer: dev_database
  environment:
    application:
      redis_url: redis://redis:6379

sftp:
  <<: *DEFAULTS
  layer: storage

cognito: &core_rails_services
  <<: *DEFAULTS
  type: Service::Rails
  layer: core
  config:
    profiles: ['scheduler', 'server', 'worker']
    ros: yes
    images: &core_rails_images
      static_gems:
        bundler: 2.0.1
        eventmachine: 1.2.7
        ffi: 1.10.0
        mini_portile2: 2.4.0
        msgpack: 1.2.10
        nio4r: 2.3.1
        nokogiri: 1.10.4
        pg: 1.1.4
        puma: 3.12.1
      development:
        build_args:
          rails_env: development
          bundle_string: --without production
          os_packages: ['libpq5', 'tree', 'curl', 'git', 'sudo', 'vim', 'less', 'tcpdump', 'net-tools', 'iputils-ping', 'graphviz']

comm:
  <<: *core_rails_services

iam:
  <<: *core_rails_services
  layer: aaa
  environment:
    self:
      platform:
        salt: 'salty value'

organization:
  <<: *core_rails_services

storage:
  <<: *core_rails_services
  layer: storage
  config:
    profiles: ['scheduler', 'server', 'sqs_worker', 'worker']
    ros: yes
    images:
      <<: *core_rails_images

<%= Cnfs::Core.project_fixture_content(__FILE__) %>
