# services.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL

localstack:
  <<: *DEFAULTS
  layer: dev_cloud
  # type: Service::Localstack
  environment:
    services: s3:4572,lambda:4574,sns:4575,sqs:4576
    port_web_ui: 8080
    debug: s3
    hostname: localstack
    hostname_external: localstack

nginx:
  <<: *DEFAULTS
  layer: routing
  # type: Service::Nginx

postgres:
  <<: *DEFAULTS
  layer: database
  environment:
    postgres_user: admin
    postgres_password: admin
    postgres_db: postgres

redis:
  <<: *DEFAULTS
  layer: database
  # type: Service::Redis

sftp:
  <<: *DEFAULTS
  layer: storage
  # type: Service::Sftp

cognito: &core_rails_services
  <<: *DEFAULTS
  layer: core
  profiles: ['scheduler', 'server', 'worker']
  ros: yes
  type: Service::Rails

comm:
  <<: *core_rails_services

iam:
  <<: *core_rails_services
  layer: aaa
  environment:
    platform:
      salt: 'salty value'

organization:
  <<: *core_rails_services

storage:
  <<: *core_rails_services
  layer: storage
  profiles: ['scheduler', 'server', 'sqs_worker', 'worker']

<%= Cnfs::Core.project_fixture_content(__FILE__) %>
