# targets.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL
  runtime: compose
  provider: localstack
  config:
    application_environment: development

development: &development
  <<: *DEFAULTS 
  # type: Target::Docker
  # generator: Generator::Compose
  services: localstack, postgres, redis, nginx, wait
  resources: instance # instance resource contains dns records, alb, instance, etc
  # layers: dev_cloud, cloud_networking, cluster, dev_cluster, cluster_database # dev_database
  config:
    application_environment: development
    mount: yes
    # dns_root_domain: localhost
    dns_root_domain: demo.cnfs.io
    dns_sub_domain: development
    lb_dns_hostnames: ['api']
    root_domain_managed_in_route53: yes
  environment:
    from_target: target_value

test: &test
  <<: *DEFAULTS 

production: &production
  <<: *DEFAULTS 
  resources: postgres, redis, kubernetes
  runtime: skaffold
  infra_runtime: terraform
  config:
    application_environment: production
    dns_root_domain: infra-testing.perxtech.io
    dns_sub_domain: development
    root_domain_managed_in_route53: yes
    lb_dns_hostnames: ['api']
  tf_config:
    tags:
      environment: staging

<%= Cnfs.config_content(:project, __FILE__) %>
<%= Cnfs.config_content(:user, __FILE__) %>
