# targets.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL

production: &production
  <<: *DEFAULTS 
  layers: cluster, cloud_networking
  runtime: skaffold

test: &test
  name: $LABEL
  runtime: compose
  provider: localstack

development_image:
  <<: *test

development:
  <<: *test
  layers: dev_cloud, cloud_networking, cluster, dev_cluster, cluster_database # dev_database
  # provider: aws_sg
  tf_config:
    tags:
      environment: staging
  config:
    mount: yes
    # dns_root_domain: localhost
    dns_root_domain: demo.cnfs.io
    dns_sub_domain: development
    root_domain_managed_in_route53: yes
    lb_dns_hostnames: ['api']
  environment:
    application:
      rails_env: development

infra-testing:
  <<: *test
  layers: cloud_networking, dev_cluster
  provider: localstack
  infra_runtime: terraform
  tf_config:
    tags:
      environment: staging
  config:
    # mount: yes
    # dns_root_domain: localhost
    dns_root_domain: infra-testing.perxtech.io
    dns_sub_domain: development
    root_domain_managed_in_route53: yes
    lb_dns_hostnames: ['api']
  environment:
    application:
      rails_env: development

<%= Cnfs::Core.project_fixture_content(__FILE__) %>
