# targets.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL
  runtime: compose
  provider: localstack
  config:
    environment: development

development: &development
  <<: *DEFAULTS 
  # type: Target::Docker
  # generator: Generator::Compose
  services: localstack, postgres, redis, nginx, wait
  resources: instance # resource contains dns records, alb, instance, etc
  # layers: dev_cloud, cloud_networking, cluster, dev_cluster, cluster_database # dev_database
  config:
    environment: development
    mount: yes
    # dns_root_domain: localhost
    dns_root_domain: demo.cnfs.io
    dns_sub_domain: development
    lb_dns_hostnames: ['api']
    root_domain_managed_in_route53: yes

test: &test
  <<: *DEFAULTS 

production: &production
  <<: *DEFAULTS 
  # layers: cluster, cloud_networking
  runtime: skaffold
  infra_runtime: terraform
  config:
    environment: production
    dns_root_domain: infra-testing.perxtech.io
    dns_sub_domain: development
    root_domain_managed_in_route53: yes
    lb_dns_hostnames: ['api']
  tf_config:
    tags:
      environment: staging

<%= Cnfs::Core.fixture_content(:project, __FILE__) %>
<%= Cnfs::Core.fixture_content(:user, __FILE__) %>
