# targets.yml
---
DEFAULTS: &DEFAULTS
  name: $LABEL

production: &production
  <<: *DEFAULTS 
  layers: cluster, networking
  runtime: skaffold

test: &test
  name: $LABEL
  runtime: compose
  provider: localstack

development_image:
  <<: *test

development:
  <<: *test
  layers: dev_cloud, dev_database
  config:
    mount: yes
    # dns_root_domain: localhost
    dns_root_domain: demo.cnfs.io
    dns_sub_domain: development
  environment:
    application:
      rails_env: development


<%= Cnfs::Core.project_fixture_content(__FILE__) %>
